'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowRight,BookOpen,GraduationCap,MessageCircle,Route,Plus} from 'lucide-react';
import {useTutor} from '@/shared/context';
import {askTutor} from './adapter';
import {SourceLinks} from '@/components/common';
import {skills,lessons} from '../../../data/learning.mjs';
import {buildPath,diagnosisComplete} from '../../../src/mastery.mjs';
export default function ChatWorkspace({compact=false}:{compact?:boolean}){
 const {state,update,navigate,notify}=useTutor();const [draft,setDraft]=useState(''),[mode,setMode]=useState<'explain'|'coach'>('explain');const last=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null);
 const conversation=state.conversations.find(c=>c.id===state.activeConversation),messages=conversation?.messages||[];
 const skill=skills.find(s=>s.id===state.selectedSkill)!,path=buildPath(state.attempts,state.minutes),recommended=path[0];
 useEffect(()=>{if(messages.length)last.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages.length]);
 useEffect(()=>{const fn=(e:Event)=>{setDraft((e as CustomEvent<string>).detail);input.current?.focus();};window.addEventListener('tutor-question',fn);return()=>window.removeEventListener('tutor-question',fn);},[]);
 function send(question:string){const text=question.trim().slice(0,2000);if(!text)return;try{const response=askTutor({question:text,context:conversation?.context||{},pricing:state.pricing,skill:state.selectedSkill,mode,history:messages});const id=conversation?.id||crypto.randomUUID();update(s=>{const existing=s.conversations.find(c=>c.id===id);const c={id,title:existing?.title||text.slice(0,32),context:response.context,messages:[...(existing?.messages||[]),{role:'user' as const,text},{role:'assistant' as const,...response}].slice(-40)};return {...s,activeConversation:id,conversations:[...s.conversations.filter(c=>c.id!==id),c].slice(-10)};});setDraft('');}catch{notify('暂时无法生成回答，请缩短问题后重试。');}}
 return <div className={`chat-workspace ${compact?'compact-chat':''} ${messages.length?'has-messages':''}`}>{messages.length?<div className="conversation" role="log" aria-label="学习对话">{messages.map((m,i)=><article key={i} className={`message message-${m.role}`}><div className="message-label">{m.role==='assistant'?<><GraduationCap size={20}/><strong>学习助手</strong><small>教材与规则</small></>:<span>我</span>}</div><div className="message-text">{m.text}</div>{m.role==='assistant'&&<SourceLinks ids={m.sourceIds||[]}/>}</article>)}<div ref={last}/></div>:<div className="welcome"><div className="welcome-mark"><GraduationCap size={43} strokeWidth={1.15}/></div><p className="eyebrow">每一次理解，都离岗位更近一步</p><h1>{compact?'从这一页，继续追问。':'今天，想学懂什么？'}</h1><p className="welcome-subtitle">你的电子商务运营学习伙伴<br className="mobile-only"/> · 从知识理解到真实任务</p></div>}
 <div className="composer-area"><form className="composer" onSubmit={e=>{e.preventDefault();send(draft);}}><textarea ref={input} aria-label="向学习助手提问" placeholder={compact?'对这节内容有什么疑问？':'问一个问题，或告诉我你正在遇到的学习困难…'} rows={compact?3:3} maxLength={2000} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(draft);}}}/><div className="composer-toolbar"><label className="mode-picker"><MessageCircle size={16}/><select aria-label="讲解方式" value={mode} onChange={e=>setMode(e.target.value as 'explain'|'coach')}><option value="explain">讲解与答疑</option><option value="coach">引导式学习</option></select></label><span className="composer-divider"/><label className="context-picker"><BookOpen size={15}/><select aria-label="当前学习主题" value={state.selectedSkill} onChange={e=>update({selectedSkill:e.target.value})}>{skills.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><button type="submit" className="send-button" aria-label="发送问题" disabled={!draft.trim()}><ArrowUp size={19}/></button></div></form>
 <div className="chat-caption">回答依据内置教材知识与规则生成 · 可点击来源核对</div>
 {messages.length?<div className="suggestions">{(messages.at(-1)?.suggestions||[]).map(q=><button key={q} onClick={()=>send(q)}>{q}<ArrowRight size={12}/></button>)}<button onClick={()=>{update({activeConversation:null});setDraft('');}}><Plus size={13}/>新对话</button></div>:<><div className="starter-grid">{[{icon:Route,text:'为我规划今天的学习',action:()=>navigate(diagnosisComplete(state.attempts)?'mastery':'diagnosis')},{icon:BookOpen,text:'降价了，为什么利润没涨？',action:()=>send('为什么收入不等于利润？')},{icon:GraduationCap,text:'给我讲一个岗位里的例子',action:()=>send(lessons.find(l=>l.skill===skill.id)!.prompt+' 举个例子')}].map(({icon:Icon,text,action})=><button key={text} onClick={action}><Icon size={17} strokeWidth={1.5}/><span>{text}</span><ArrowRight size={13}/></button>)}</div>{!compact&&<div className="continue-learning"><div className="continue-icon"><Route size={20}/></div><div><span>{diagnosisComplete(state.attempts)?'根据你的作答，继续下一步':'还不了解自己的起点？'}</span><strong>{diagnosisComplete(state.attempts)?recommended?.lesson?.title:'用 6 道小题，找到适合自己的学习路径'}</strong></div><button onClick={()=>navigate(diagnosisComplete(state.attempts)?'mastery':'diagnosis')}>{diagnosisComplete(state.attempts)?'查看路径':'开始诊断'}<ArrowRight size={15}/></button></div>}</>}
 </div>{!messages.length&&!compact&&<div className="home-footnote"><span>财经商贸专业群</span><span>电子商务运营专员</span><span>65 条有来源的专业知识</span></div>}</div>;
}
