'use client';
// Adapted from DeepTutor 1.6.7 AppShell.tsx (Apache-2.0). See licenses/DeepTutor-NOTICE.md.
import {useEffect,useRef,useState} from 'react';
import {House,Route,BookText,ChartNoAxesCombined,LayoutGrid,Brain,BookOpen,Settings,PanelLeftClose,PanelLeftOpen,Menu,X,Plus,MessageCircle,ArrowUpRight,GraduationCap,HelpCircle} from 'lucide-react';
import type {View} from '@/contracts/learning';
import {useTutor} from '@/shared/context';
const primary=[['home','学习首页',House],['mastery','学习路径',Route],['reading','沉浸阅读',BookText],['workspace','岗位实训',ChartNoAxesCombined],['space','学习空间',LayoutGrid]] as const;
const secondary=[['memory','学习记忆',Brain],['knowledge','知识中心',BookOpen],['settings','设置',Settings]] as const;
const titles:Record<View,string>={home:'新的学习对话',mastery:'学习路径',reading:'沉浸阅读',workspace:'岗位实训',space:'学习空间',memory:'学习记忆',knowledge:'知识中心',settings:'设置',guide:'体验说明',diagnosis:'学习诊断',practice:'迁移练习'};
export default function AppShell({view,children}:{view:View;children:React.ReactNode}){
 const {state,update,navigate}=useTutor();const [open,setOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false);const toggle=useRef<HTMLButtonElement>(null),drawer=useRef<HTMLElement>(null);
 useEffect(()=>{const m=matchMedia('(max-width: 767px)');setMobile(m.matches);const fn=()=>{setMobile(m.matches);setOpen(false);};m.addEventListener('change',fn);return ()=>m.removeEventListener('change',fn);},[]);
 useEffect(()=>{setOpen(false);},[view]);
 useEffect(()=>{if(!open||!mobile)return;drawer.current?.querySelector<HTMLElement>('button')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}if(e.key==='Tab'){const nodes=drawer.current?.querySelectorAll<HTMLElement>('button,a[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[open,mobile]);
 const go=(v:View)=>{navigate(v);setOpen(false);if(mobile)toggle.current?.focus();};
 const newChat=()=>{update({activeConversation:null});go('home');};
 return <div className={`app-shell ${collapsed?'collapsed':''}`}><a className="skip-link" href="#main-content">跳到主要内容</a>{open&&mobile&&<div className="drawer-scrim" onClick={()=>{setOpen(false);toggle.current?.focus();}}/>}<aside ref={drawer} className={`sidebar ${open?'drawer-open':''}`} inert={mobile&&!open?true:undefined} aria-label="学习导航">
 <div className="brand-row"><button className="brand" onClick={()=>go('home')} aria-label="职教自适应学习助手首页"><span className="brand-icon"><GraduationCap size={25} strokeWidth={1.45}/></span><span className="brand-copy">职教自适应<span>学习助手</span></span></button><button className="icon-button sidebar-toggle" aria-label={mobile?'关闭导航':collapsed?'展开侧栏':'收起侧栏'} onClick={()=>mobile?setOpen(false):setCollapsed(!collapsed)}>{mobile?<X size={17}/>:collapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</button></div>
 <button className="new-chat" onClick={newChat}><Plus size={17}/><span>开始新对话</span></button><nav>{primary.map(([v,label,Icon])=><button key={v} title={label} className="nav-item" aria-current={view===v||(v==='mastery'&&['diagnosis','practice'].includes(view))?'page':undefined} onClick={()=>go(v)}><Icon size={18} strokeWidth={1.65}/><span>{label}</span>{v==='mastery'&&<small>学习</small>}</button>)}</nav>
 <div className="recent"><span className="nav-caption">最近对话</span>{state.conversations.length===0?<p>从一个问题开始，<br/>留下自己的学习轨迹。</p>:[...state.conversations].reverse().slice(0,4).map(c=><button key={c.id} className="history-item" onClick={()=>{update({activeConversation:c.id});go('home');}}><MessageCircle size={14}/><span>{c.title}</span></button>)}</div>
 <div className="sidebar-bottom"><nav>{secondary.map(([v,label,Icon])=><button key={v} title={label} className="nav-item" aria-current={view===v?'page':undefined} onClick={()=>go(v)}><Icon size={18} strokeWidth={1.65}/><span>{label}</span></button>)}</nav><div className="sidebar-footer"><span className="avatar">学</span><div><strong>我的学习工作台</strong><span>电子商务 · 运营岗位</span></div><button className="icon-button" title="体验说明" aria-label="体验说明" onClick={()=>go('guide')}><HelpCircle size={17}/></button></div></div></aside>
 <div className="main-shell"><header className="topbar"><div><button ref={toggle} className="icon-button mobile-menu" aria-label="打开导航" aria-expanded={open} onClick={()=>setOpen(true)}><Menu size={19}/></button><span>{titles[view]}</span></div><div><span className="demo-indicator"><i/>公开体验版</span><button className="icon-button" title="使用说明" aria-label="使用说明" onClick={()=>go('guide')}><HelpCircle size={18}/></button><a className="icon-button" title="项目代码" aria-label="项目代码" href="https://github.com/lzh-ff/kedaxunfei" target="_blank" rel="noopener noreferrer"><ArrowUpRight size={19}/></a></div></header><main id="main-content" tabIndex={-1} className={`main-content view-${view}`}>{children}</main></div></div>;
}
