import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {computeMastery,validAttempts,masteryProfile,buildPath,diagnosisComplete} from '../src/mastery.mjs';
import {questions,allQuestions,lessons,skills} from '../data/learning.mjs';
import {knowledge,sources} from '../data/knowledge.mjs';
const at='2026-09-12T12:00:00.000Z';
const answer=(id,correct=true)=>{const q=allQuestions.find(q=>q.id===id);return {questionId:id,choice:correct?q.answer:(q.answer+1)%q.options.length,at};};
test('browser algorithm matches actual upstream Python for all 511 boolean histories up to length 8',()=>{
 const vectors=[];for(let len=0;len<=8;len++)for(let n=0;n<2**len;n++)vectors.push(Array.from({length:len},(_,i)=>Boolean(n&(1<<i))));
 const result=spawnSync('python',['-c','import json,sys; from server.vendor.deeptutor_mastery import compute_mastery; print(json.dumps([compute_mastery(v) for v in json.load(sys.stdin)]))'],{input:JSON.stringify(vectors),encoding:'utf8'});
 assert.equal(result.status,0,result.stderr);const expected=JSON.parse(result.stdout);vectors.forEach((v,i)=>assert.ok(Math.abs(computeMastery(v)-expected[i])<1e-12,JSON.stringify(v)));
});
test('one lucky answer is capped, two answers do not complete a skill',()=>{assert.equal(computeMastery([true]),.5);assert.equal(computeMastery([true,true]),.8);const s=masteryProfile([answer('q1'),answer('p-demand-1')])[0];assert.equal(s.mastered,false);assert.equal(s.score,80);});
test('three different correct questions reach the gate; duplicate attempts cannot inflate evidence',()=>{const a=[answer('q1'),answer('p-demand-1'),answer('p-demand-2')];assert.equal(masteryProfile(a)[0].mastered,true);assert.equal(masteryProfile(Array.from({length:30},()=>answer('q1')))[0].score,50);});
test('a latest wrong answer changes evidence and removes mastered status',()=>{const a=[answer('q1'),answer('p-demand-1'),answer('p-demand-2'),answer('p-demand-2',false)];const s=masteryProfile(a)[0];assert.equal(s.evidence.length,3);assert.equal(s.mastered,false);assert.ok(s.score<80);});
test('invalid stored records are discarded rather than credited',()=>{const valid=answer('q1');assert.deepEqual(validAttempts([{...valid,choice:99},{...valid,at:'nope'},{...valid,questionId:'__proto__'},null,valid]),[valid]);assert.throws(()=>computeMastery([1]),TypeError);});
test('empty profile and partial diagnosis never claim complete',()=>{assert.ok(masteryProfile([]).every(s=>s.status==='待诊断'));assert.equal(diagnosisComplete([answer('q1')]),false);assert.equal(diagnosisComplete(questions.map(q=>answer(q.id))),true);});
test('path respects time, prioritizes weak topics and prerequisite ordering',()=>{const wrongCost=allQuestions.map(q=>answer(q.id,q.skill!=='cost'));const p=buildPath(wrongCost,30);assert.equal(p[0].id,'cost');const empty=buildPath([],60);assert.ok(empty.reduce((a,s)=>a+s.lesson.minutes,0)<=60);assert.ok(empty.findIndex(s=>s.id==='demand')<empty.findIndex(s=>s.id==='pricing'));assert.ok(buildPath([],30).length<buildPath([],60).length);});
test('time budget cannot skip a prerequisite and still recommend its dependent course',()=>{const a=questions.map(q=>answer(q.id,!['demand','ethics'].includes(q.skill)));const p=buildPath(a,30);assert.deepEqual(p.map(s=>s.id),['demand','ethics']);});
test('every question and lesson links to an existing sourced knowledge entry',()=>{assert.equal(allQuestions.length,18);assert.equal(new Set(allQuestions.map(q=>q.id)).size,18);for(const s of skills)assert.equal(allQuestions.filter(q=>q.skill===s.id).length,3);for(const q of allQuestions){const k=knowledge.find(k=>k.id===q.knowledgeId);assert.ok(k&&sources[k.sourceId],q.id);assert.ok(q.answer>=0&&q.answer<q.options.length);}for(const l of lessons)for(const id of l.knowledgeIds)assert.ok(knowledge.some(k=>k.id===id));});
