'use client';
import {useState} from 'react';
import {ArrowDownToLine,ArrowRight,RotateCcw,SlidersHorizontal,FlaskConical} from 'lucide-react';
import {useTutor} from '@/shared/context';
import {PageHeading,SourceLinks} from '@/components/common';
import {scenarios} from '../../../data/curriculum.mjs';
import {createTask,defaults,simulatePricing} from '../../../src/engine.mjs';
import {pricingResults,gameResults} from '../../../src/views.mjs';
export default function PracticumView(){const {state,update,exportReport,navigate,notify}=useTutor();const task=createTask({scenario:state.scenario,level:state.level,minutes:state.minutes});const [scenario,setScenario]=useState(state.scenario),[level,setLevel]=useState(state.level),[game,setGame]=useState({belief:.5,kappa:.5});
 function price(key:string,value:number){try{simulatePricing({...state.pricing,[key]:value});update({pricing:{...state.pricing,[key]:value}});}catch{notify('请输入有效范围内的经营参数。');}}
 return <div className="page-container practicum"><PageHeading eyebrow="JOB PRACTICUM · 学以致用" title="把知识，放进一次经营决策。" description="调整变量、比较方案、写出依据，完成一份自己的运营分析。"><button className="button" onClick={exportReport}><ArrowDownToLine size={16}/>导出实训报告</button></PageHeading>
 <section className="task-banner"><div><span className="eyebrow">当前任务 · 教学模拟店铺</span><h2>{task.title}</h2><p>{task.brief}</p></div><span className="status-tag">{task.level} · {task.minutes} 分钟</span><form className="task-controls" onSubmit={e=>{e.preventDefault();update({scenario,level,steps:[],...(scenario==='inventory'?{pricing:{...state.pricing,capacity:1100}}:{})});notify('学习任务及评价要求已更新。');}}><label>业务情境<select aria-label="业务情境" value={scenario} onChange={e=>setScenario(e.target.value)}>{Object.entries(scenarios).map(([id,s])=><option value={id} key={id}>{s.short}</option>)}</select></label><label>学习层级<select aria-label="学习层级" value={level} onChange={e=>setLevel(e.target.value)}><option>基础</option><option>进阶</option></select></label><button className="button primary" type="submit">生成学习任务<ArrowRight size={14}/></button></form></section>
 <div className="practicum-grid"><section className="experiment"><div className="section-heading"><div><h2><SlidersHorizontal size={19}/>经营变量实验</h2><p>一次改变一个条件，观察结果如何变化。</p></div><button className="text-button" onClick={()=>update({pricing:{...defaults,price:100}})}><RotateCcw size={14}/>恢复基准</button></div><div className="sliders">{[{id:'price',label:'促销售价',min:50,max:140,step:1,unit:'元'},{id:'elasticity',label:'需求弹性 |ε|',min:.2,max:3,step:.1,unit:''},{id:'unitCost',label:'单位变动成本',min:10,max:100,step:1,unit:'元'},{id:'capacity',label:'可交付库存',min:500,max:3000,step:100,unit:'件'}].map(s=><label className="slider-field" key={s.id}><span>{s.label}<output>{state.pricing[s.id]}{s.unit}</output></span><input id={s.id} type="range" min={s.min} max={s.max} step={s.step} value={state.pricing[s.id]} onChange={e=>price(s.id,Number(e.target.value))}/></label>)}</div><label className="fixed-cost">本期固定成本<input aria-label="本期固定成本" type="number" min={0} max={100000} step={1000} value={state.pricing.fixedCost} onChange={e=>{if(e.target.value!==''&&e.target.validity.valid)price('fixedCost',Number(e.target.value));}}/>元</label><div className="pricing-results" id="pricing-result" dangerouslySetInnerHTML={{__html:pricingResults({pricing:state.pricing})}}/></section>
 <aside className="task-evidence"><span className="eyebrow">学习证据</span><h2>留下一次完整的判断</h2><div className="checklist">{task.steps.map((s,i)=><label key={s}><input type="checkbox" checked={state.steps[i]||false} onChange={e=>{const steps=[...state.steps];steps[i]=e.target.checked;update({steps});}}/><span>{s}</span></label>)}</div><span className="small-muted">{state.steps.filter(Boolean).length} / {task.steps.length} 项自行确认完成</span><label className="note-field">我的经营判断<textarea id="learning-note" rows={6} maxLength={5000} value={state.note} onChange={e=>update({note:e.target.value})} placeholder="我的建议是什么？用了哪些计算依据？还需要验证哪个假设？"/></label><button className="button full" onClick={exportReport}><ArrowDownToLine size={15}/>导出当前分析</button><details className="method-note"><summary>成果要求与评价标准</summary><ul>{task.criteria.map(c=><li key={c}>{c}</li>)}</ul><p>{task.safety}</p><SourceLinks ids={task.sourceIds}/></details><button className="text-button" onClick={()=>navigate('reading','cost')}>回顾成本与利润<ArrowRight size={14}/></button></aside></div>
 <details className="game-experiment"><summary><FlaskConical size={19}/>扩展实验：同一个博弈，不同的行动准则<span>展开实验</span></summary><p>单轮囚徒困境：双方合作各得3、双方背叛各得1，单方背叛者得5、被背叛者得0。全部为合成教学收益。</p><div className="sliders">{[{id:'belief' as const,label:'相信对手合作的概率 q'},{id:'kappa' as const,label:'普遍化权重 κ'}].map(g=><label className="slider-field" key={g.id}><span>{g.label}<output>{game[g.id]}</output></span><input id={g.id} type="range" min={0} max={1} step={.05} value={game[g.id]} onChange={e=>setGame({...game,[g.id]:Number(e.target.value)})}/></label>)}</div><div id="game-result" dangerouslySetInnerHTML={{__html:gameResults({game})}}/><p className="small-muted">依据用户论文《大型语言模型智能体与理性及道德偏好的对齐：一种监督微调方法》第3.3节公式(1)，取α=β=0作教学简化。U(C)=(1−κ)qR+κR；U(D)=(1−κ)[qT+(1−q)P]+κP。本页直接计算效用，没有训练论文模型，也不用于评价人格。</p></details></div>;
}
