'use client';
import {useState} from 'react';
import {ArrowRight,Check,Clock,BookOpen,ChevronRight,Target,Route,RefreshCw,CheckCircle2} from 'lucide-react';
import {useTutor} from '@/shared/context';
import {PageHeading,SourceLinks} from '@/components/common';
import ChatWorkspace from '@/features/chat/ChatWorkspace';
import {skills,questions,lessons,practiceQuestions} from '../../../data/learning.mjs';
import {knowledge} from '../../../data/knowledge.mjs';
import {buildPath,masteryProfile,diagnosisComplete} from '../../../src/mastery.mjs';
export function MasteryView(){const {state,update,navigate}=useTutor(),profile=masteryProfile(state.attempts),path=buildPath(state.attempts,state.minutes),done=profile.filter(s=>s.mastered).length,hasDiagnosis=diagnosisComplete(state.attempts);
 return <div className="page-container"><PageHeading eyebrow="MASTERY PATH · 以岗定学" title="找到你的下一步。" description="从真实作答出发，把薄弱知识转成可完成的学习任务。"><button className="button" onClick={()=>navigate('diagnosis')}><Target size={16}/>{hasDiagnosis?'重新诊断':'开始学习诊断'}</button></PageHeading>
 <section className="path-overview"><div><span className="eyebrow">电子商务运营专员</span><h2>从市场判断，到经营决策</h2><p>六个岗位能力 · 阅读、迁移练习与实训相连</p></div><div className="progress-summary"><strong>{done}<small> / 6</small></strong><span>本组题已达标能力</span></div></section>
 {!hasDiagnosis&&<div className="inline-notice"><Target size={20}/><div><strong>先用 6 道题了解你的起点</strong><p>当前展示基础学习顺序；完成诊断后会依据作答重新安排。</p></div><button className="text-button" onClick={()=>navigate('diagnosis')}>开始诊断<ArrowRight size={15}/></button></div>}
 <section className="path-section"><div className="section-heading"><div><h2>今天的学习安排</h2><p>优先补强薄弱点，同时照顾先修知识。</p></div><label className="time-select"><Clock size={15}/>可用时间<select aria-label="可用学习时间" value={state.minutes} onChange={e=>update({minutes:Number(e.target.value)})}>{[30,45,60].map(m=><option value={m} key={m}>{m} 分钟</option>)}</select></label></div><div className="path-list">{path.map((s,i)=><article className="path-item" key={s.id}><div className="path-number">{s.mastered?<Check size={18}/>:String(i+1).padStart(2,'0')}</div><div className="path-content"><div className="path-meta"><span>{s.name}</span><span><Clock size={12}/>{s.lesson!.minutes} 分钟</span></div><h3>{s.lesson!.title}</h3><p>{s.reason}</p><div className="path-steps"><span>教材阅读</span><ChevronRight size={12}/><span>基础复核 + 2 道迁移题</span><ChevronRight size={12}/><span>更新学习证据</span></div></div><button className="button" onClick={()=>navigate('reading',s.id)}>开始学习<ArrowRight size={15}/></button></article>)}</div></section>
 <section className="path-section"><div className="section-heading"><div><h2>我的岗位能力图谱</h2><p>每项关联 3 道不同题目。题量有限，结果只反映本组练习。</p></div><span className="small-muted">随作答实时更新</span></div><div className="skill-grid">{profile.map((s,i)=><button className={`skill-card ${s.mastered?'mastered':''}`} key={s.id} onClick={()=>navigate('reading',s.id)}><div><span className="skill-index">0{i+1}</span><span className="skill-status">{s.status}</span></div><h3>{s.name}<ArrowRight size={15}/></h3><p>{s.description}</p><div className="skill-meter"><i style={{width:`${s.score}%`}}/></div><div className="skill-evidence"><span>{s.evidence.length} / 3 道不同题目</span><strong>{s.evidence.length?`${s.score}%`:'—'}</strong></div></button>)}</div><details className="method-note"><summary>学习进度是怎样计算的？</summary><p>沿用 DeepTutor 1.6.7 的近期加权正确率：最近五次证据权重为 0.5、0.7、0.85、0.95、1.0。只有一道题时最高 50%，两道题最高 80%。本作品按题目去重，重复回答同一道题不会增加证据数量；至少 3 道不同题、加权结果达到 80% 且最近答对，才标记本组达标。它不是能力认证或统计预测。</p></details></section></div>;
}
export function AssessmentView({practice=false}:{practice?:boolean}){
 const {state,update,navigate,notify}=useTutor();const quiz=practice?[...questions.filter(q=>q.skill===state.selectedSkill),...practiceQuestions.filter(q=>q.skill===state.selectedSkill)]:questions;const [answers,setAnswers]=useState<Record<string,number>>({}),[submitted,setSubmitted]=useState(false);const chosen=Object.keys(answers).length,correct=quiz.filter(q=>answers[q.id]===q.answer).length;
 function submit(e:React.FormEvent){e.preventDefault();if(chosen!==quiz.length){notify('请完成全部题目后提交。');return;}const at=new Date().toISOString();update(s=>({...s,attempts:[...s.attempts,...quiz.map(q=>({questionId:q.id,choice:answers[q.id],at}))].slice(-300)}));setSubmitted(true);notify('作答已记录，学习路径已更新。');}
 return <div className="page-container narrow"><PageHeading eyebrow={practice?'TRANSFER PRACTICE · 验证理解':'LEARNING CHECK · 找到起点'} title={practice?`${skills.find(s=>s.id===state.selectedSkill)?.name} · 迁移练习`:'先从 6 道小题开始。'} description={practice?'先复核本能力的基础题，再做2道迁移题；三道不同题共同更新学习证据。':'每项岗位能力 1 道题，不计时；提交后生成你的学习安排。'}/><div className="quiz-progress"><span>{submitted?'已提交':`已回答 ${chosen} / ${quiz.length}`}</span><div><i style={{width:`${chosen/quiz.length*100}%`}}/></div><span>{practice?'约 3 分钟':'约 5 分钟'}</span></div>
 <form onSubmit={submit} className="quiz-form">{quiz.map((q,i)=><fieldset className="question-card" key={q.id}><legend><span>0{i+1}</span>{q.text}</legend><div className="answer-options">{q.options.map((o,idx)=><label key={o} className={`${answers[q.id]===idx?'selected':''} ${submitted&&q.answer===idx?'correct':''} ${submitted&&answers[q.id]===idx&&q.answer!==idx?'incorrect':''}`}><input type="radio" disabled={submitted} name={q.id} value={idx} required checked={answers[q.id]===idx} onChange={()=>setAnswers({...answers,[q.id]:idx})}/><span className="option-letter">{'ABC'[idx]}</span><span>{o}</span>{submitted&&q.answer===idx&&<Check size={16}/>}</label>)}</div>{submitted&&<div className="answer-explanation"><strong>{answers[q.id]===q.answer?'回答正确':'再理解一下'}</strong><p>{q.explanation}</p><button type="button" className="text-button" onClick={()=>navigate('reading',q.skill)}>回到相关讲解<ArrowRight size={13}/></button></div>}</fieldset>)}{!submitted?<button type="submit" className="button primary quiz-submit">提交{practice?'练习':'诊断'}，更新学习路径<ArrowRight size={16}/></button>:<div className="quiz-result"><CheckCircle2 size={28}/><div><h2>答对 {correct} / {quiz.length} 题</h2><p>新证据已加入学习记忆。{correct<quiz.length?'薄弱题对应的知识已进入后续学习安排。':'继续用不同情境的题目巩固理解。'}</p></div><button className="button primary" type="button" onClick={()=>navigate('mastery')}>查看更新后的路径<ArrowRight size={16}/></button><button className="text-button" type="button" onClick={()=>{setAnswers({});setSubmitted(false);}}>再练一次<RefreshCw size={14}/></button></div>}</form></div>;
}
export function ReadingView(){const {state,update,navigate,openKnowledge,ask,notify}=useTutor();const lesson=lessons.find(l=>l.skill===state.selectedSkill)!,entries=lesson.knowledgeIds.map(id=>knowledge.find(k=>k.id===id)!);const read=state.reads.includes(lesson.skill);return <div className="reading-layout"><aside className="reading-outline"><span className="eyebrow">岗位学习手册</span><h2>电商运营的<br/>经济学基础</h2><p>6 个学习单元</p><nav aria-label="学习单元">{lessons.map((l,i)=><button className={l.skill===lesson.skill?'active':''} key={l.skill} onClick={()=>navigate('reading',l.skill)}><span>0{i+1}</span><span>{skills.find(s=>s.id===l.skill)?.name}</span>{state.reads.includes(l.skill)&&<Check size={13}/>}</button>)}</nav><div className="outline-note"><BookOpen size={17}/><span>OpenStax 教材改写<br/>原创岗位案例</span></div></aside><article className="reading-article"><div className="reading-meta"><span>{skills.find(s=>s.id===lesson.skill)?.name}</span><span><Clock size={13}/>{lesson.minutes} 分钟</span></div><h1>{lesson.title}</h1><p className="article-subtitle">{lesson.subtitle}</p><div className="learning-objective"><Target size={19}/><div><strong>这一节，你将学会</strong><p>{lesson.objective}</p></div></div><h2>01 从岗位中的一个问题开始</h2><p>{lesson.case}</p><h2>02 把概念讲清楚</h2>{entries.slice(0,3).map(k=><section className="reading-concept" key={k.id}><h3>{k.title}<button className="text-button" onClick={()=>openKnowledge(k.id)}>{k.id}<ArrowRight size={12}/></button></h3><p>{k.text}</p><SourceLinks ids={[k.sourceId]}/></section>)}<h2>03 一起拆解这次判断</h2><div className="worked-example"><p>{lesson.worked}</p></div><h3>容易混淆的地方</h3><p>{lesson.mistake}</p><div className="reading-actions"><button className="button" onClick={()=>{if(!read)update({reads:[...state.reads,lesson.skill]});notify('阅读已记录；掌握度需要通过作答验证。');}}><Check size={16}/>{read?'已记录阅读':'标记本节已读'}</button><button className="button primary" onClick={()=>navigate('practice')}>复核与迁移练习<ArrowRight size={16}/></button></div><p className="small-muted">中文教学改写，案例为模拟情境。阅读记录不直接增加掌握度。</p><SourceLinks ids={entries.map(k=>k.sourceId)}/></article><aside className="reading-tutor"><div className="reading-tutor-header"><GraduationCapMark/><strong>随读导师</strong><button className="text-button" onClick={()=>ask(lesson.prompt)}>问这一节<ArrowRight size={13}/></button></div><ChatWorkspace compact/></aside></div>;
}
function GraduationCapMark(){return <BookOpen size={18}/>;}
