import {knowledge,sources} from '../data/knowledge.mjs';
import {skills,questions,scenarios} from '../data/curriculum.mjs';
import {simulatePricing,describeBreakEven,pricingCurve,evaluateGame,diagnose,searchKnowledge} from './engine.mjs';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const number=(n,d=0)=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d});
export function sourceLinks(ids){return [...new Set(ids)].filter(id=>sources[id]).map(id=>`<a class="source-link" href="${esc(sources[id].url)}" target="_blank" rel="noopener noreferrer">${sources[id].title.startsWith('Open')?'OpenStax':id==='nash'?'MIT OCW':'教育部教学标准'} §${esc(sources[id].section.split(' ')[0])} <span>↗</span></a>`).join('');}
const heading=(tag,title,description,action='')=>`<div class="page-heading"><div><div class="eyebrow">${tag}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
export function pricingResults(state){
 const r=simulatePricing(state.pricing),curve=pricingCurve(state.pricing);
 const min=Math.min(0,...curve.map(p=>p.profit)),max=Math.max(...curve.map(p=>p.profit),1),spread=max-min||1;
 const x=p=>48+(p-50)/90*574,y=p=>205-(p-min)/spread*160;
 const line=curve.map((p,i)=>`${i?'L':'M'}${x(p.price).toFixed(1)},${y(p.profit).toFixed(1)}`).join(' ');
 const ticks=Array.from({length:5},(_,i)=>min+spread*i/4);
 return `<div class="metric-grid"><div><span>模型销量 <small>件 / 期</small></span><strong data-metric="quantity">${number(r.quantity)}</strong><small>${r.constrained?'已受可交付库存限制':'按恒定需求弹性估算'}</small></div><div><span>模型收入 <small>元 / 期</small></span><strong>${number(r.revenue)}</strong><small>售价 × 可实现销量</small></div><div class="metric-primary"><span>模型利润 <small>元 / 期</small></span><strong data-metric="profit">${number(r.profit)}</strong><small class="${r.delta>=0?'positive':'negative'}">${Math.abs(r.delta)<.005?'与基准相同':`${r.delta>0?'↑':'↓'} 比基准${r.delta>0?'增加':'减少'} ${number(Math.abs(r.delta))} 元`}</small></div></div>
 <div class="chart-header"><h3>价格改变，利润如何变化</h3><span><i></i> 模型利润曲线</span></div>
 <svg class="pricing-chart" viewBox="0 0 660 258" role="img" aria-label="价格50到140元对应的模型利润曲线，当前利润${number(r.profit)}元"><text x="8" y="17" class="axis-label">利润 / 万元</text>${ticks.map(t=>`<line class="grid-line" x1="48" x2="622" y1="${y(t)}" y2="${y(t)}"/><text x="40" y="${y(t)+4}" text-anchor="end" class="axis-label">${number(t/10000,1)}</text>`).join('')}
 <path d="${line}" fill="none" stroke="#386453" stroke-width="3" stroke-linejoin="round"/>
 <line x1="${x(r.params.price)}" x2="${x(r.params.price)}" y1="38" y2="205" stroke="#98aaa1" stroke-dasharray="4 5"/><circle cx="${x(r.params.price)}" cy="${y(r.profit)}" r="6" fill="#386453" stroke="white" stroke-width="3"/>
 ${[50,65,80,95,110,125,140].map(p=>`<text x="${x(p)}" y="227" class="axis-label" text-anchor="middle">${p}</text>`).join('')}<text x="622" y="249" text-anchor="end" class="axis-label">售价 / 元</text></svg>
 <div class="result-note ${r.constrained?'warning':''}"><strong>${r.constrained?'库存约束已触发':Math.abs(r.delta)<.005?'当前利润与基准相同。':r.delta<0?'销量与利润，需要分开判断。':'当前方案的利润高于基准。'}</strong><p>${r.constrained?`潜在需求约${number(r.unconstrainedDemand)}件，可实现销量仅${number(r.quantity)}件；继续降价不一定带来可交付订单。`:`每件贡献${number(r.margin,2)}元；${describeBreakEven(r)} 基准利润${number(r.baselineProfit)}元。`}</p></div>
 <details class="model-details"><summary>计算公式与适用边界</summary><p>潜在需求 Q = Q₀ × (P / P₀)<sup>−ε</sup>；可实现销量 = min(Q, 库存)；利润 = (P − 单位变动成本) × 可实现销量 − 固定成本。</p><p>本例 P₀=100元，Q₀=1000件。数量为连续期望值，界面四舍五入显示；假设需求弹性、单位成本和分析周期不变，未单列税费、退款、平台抽佣、现金流和竞争反应。不是现实销量预测或自动经营建议。</p>${sourceLinks(['elasticity','revenue','costs'])}</details>`;
}
function slider(id,label,value,min,max,step,unit){return `<label class="slider-field" for="${id}"><span>${label}<output id="${id}-value">${value}${unit}</output></span><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}" data-pricing="${id}"></label>`;}
export function workspaceView(state){
 const t=state.task,done=state.steps.filter(Boolean).length;
 return heading('以岗定教 · 运营决策实训','把经济学，放进一次经营决策。','完成一次促销分析，学会从“卖得更多”走向“判断有据”。',`<button class="button secondary" data-action="export-report">导出实训报告 <span aria-hidden="true">↗</span></button>`)+
 `<div class="workspace-grid"><div class="work-column"><section class="task-panel"><div class="section-kicker"><span>当前学习任务</span><span class="tag">${esc(t.level)} · ${t.minutes}分钟</span></div><h2>${esc(t.title)}</h2><p>${esc(t.brief)}</p>
 <form id="task-form" class="task-controls"><label>业务情境<select name="scenario">${Object.entries(scenarios).map(([id,s])=>`<option value="${id}" ${id===t.scenario?'selected':''}>${s.short}</option>`).join('')}</select></label><label>学习层级<select name="level"><option ${t.level==='基础'?'selected':''}>基础</option><option ${t.level==='进阶'?'selected':''}>进阶</option></select></label><label>课时<select name="minutes">${[30,45,60].map(m=>`<option value="${m}" ${m===t.minutes?'selected':''}>${m}分钟</option>`).join('')}</select></label><button class="button primary" type="submit">生成学习任务</button></form>
 <div class="task-bottom"><span>任务流程：确认数据 → 比较方案 → 解释结果 → 提交分析</span><button class="text-button" data-action="task-details">查看任务要求 ↗</button></div></section>
 <section class="panel experiment-panel"><div class="panel-heading"><div><span class="section-kicker">交互实验</span><h2>试着改变一个经营变量</h2></div><span class="tag neutral">教学模拟数据</span></div><div class="sliders">${slider('price','促销售价',state.pricing.price,50,140,1,'元')}${slider('elasticity','需求弹性 |ε|',state.pricing.elasticity,.2,3,.1,'')}${slider('unitCost','单位变动成本',state.pricing.unitCost,10,100,1,'元')}${slider('capacity','可交付库存',state.pricing.capacity,500,3000,100,'件')}</div><div class="fixed-row"><label for="fixedCost">本期固定成本 <input id="fixedCost" type="number" min="0" max="100000" step="1000" value="${state.pricing.fixedCost}" data-pricing="fixedCost"> 元</label><button class="text-button" data-action="reset-pricing">恢复基准参数</button></div><div id="pricing-result">${pricingResults(state)}</div></section>
 <section class="panel task-check"><div class="panel-heading"><h2>让一次尝试，留下学习证据</h2><span id="steps-counter">${done} / ${t.steps.length} 已完成</span></div><div class="checklist">${t.steps.map((s,i)=>`<label><input type="checkbox" data-step="${i}" ${state.steps[i]?'checked':''}><span><b>${String(i+1).padStart(2,'0')}</b>${esc(s)}</span></label>`).join('')}</div><label class="note-label" for="learning-note">我的经营判断与待验证假设</label><textarea id="learning-note" rows="3" placeholder="例如：当前降价带来的销量增加不足以抵消单位贡献下降。我还需要核实真实需求弹性及退款成本。">${esc(state.note)}</textarea><p class="fine-print">勾选表示你自行确认完成，不等于教师评价。报告包含当前参数、计算结果、来源和你的分析。</p></section></div>
 <aside class="tutor-column"><section class="panel tutor"><div class="tutor-heading"><span class="tutor-avatar">知</span><div><h2>实训导师</h2><small>知识检索 · 步骤引导 · 依据溯源</small></div></div><div class="engine-label">知识与规则生成 · 无外部模型调用</div><div id="messages" class="messages" role="log" aria-label="导师对话" aria-live="polite">${messagesView(state)}</div><div class="suggestions" id="chat-suggestions">${suggestionButtons(state)}</div><form id="chat-form"><label class="sr-only" for="chat-input">向实训导师提问</label><textarea id="chat-input" maxlength="1000" rows="2" placeholder="问一问：降价一定能提高利润吗？"></textarea><div><small>Enter 发送 · Shift+Enter 换行</small><button class="send-button" type="submit" aria-label="发送问题">↑</button></div></form></section>
 <section class="learning-next"><div class="section-kicker">你的下一步</div><h3>先发现盲点，再决定学什么。</h3><p>6道岗位情境题，检查需求、定价、成本等关键知识。</p><button class="button secondary" data-action="start-diagnosis">开始学习诊断 <span>→</span></button></section><div class="source-summary"><strong>${knowledge.length}条专业知识 · ${Object.keys(sources).length}个来源入口</strong><p>OpenStax 经济学教材 · MIT博弈论讲义<br>教育部电子商务专业教学标准</p><button class="text-button" data-action="open-knowledge">浏览知识与来源 ↗</button></div></aside></div>`;
}
export function suggestionButtons(state){const a=state.messages.filter(m=>m.role==='assistant').at(-1);return (a?.suggestions||['降价一定能提高利润吗？','需求价格弹性是什么？','这个怎么弄？']).map(q=>`<button data-question="${esc(q)}">${esc(q)}</button>`).join('');}
export function messagesView(state){return `<div class="message assistant"><span class="message-label">实训导师</span><p>从左边的任务开始吧。调整售价后，注意销量和利润是否同向变化。你也可以问我一个概念，再追问例子和依据。</p></div>`+state.messages.map(m=>`<div class="message ${m.role}"><span class="message-label">${m.role==='user'?'你':'实训导师 · 知识与规则生成'}</span><p>${esc(m.text).replace(/\n/g,'<br>')}</p>${m.sourceIds?.length?`<div class="message-sources">${sourceLinks(m.sourceIds)}</div>`:''}</div>`).join('');}
export function mapView(state){const d=diagnose(state.answers);return heading('岗位能力图谱','从一份工作，看见要学的知识。','以电子商务运营专员为核心，连接工作任务、能力单元与教材知识点。')+`<section class="map-root"><span class="tag">财经商贸专业群</span><h2>电子商务运营专员</h2><p>典型工作任务：促销分析、经营复盘与库存约束下的活动决策</p><div>${sourceLinks(['standard'])}</div></section><div class="map-connector" aria-hidden="true"></div><div class="competency-grid">${d.dimensions.map((s,i)=>`<article class="panel competency-card"><div class="competency-number">${String(i+1).padStart(2,'0')}</div><h2>${s.name}</h2><p>${s.description}</p><div class="skill-status">${s.score===null?'尚未测评':s.score===100?'本次诊断题答对':'本次诊断题需复习'}</div><h3>关联知识点</h3>${s.resources.map(id=>{const k=knowledge.find(k=>k.id===id);return `<button class="knowledge-row" data-knowledge="${id}">${esc(k?.title||id)} <span>↗</span></button>`;}).join('')}<button class="text-button" data-skill="${s.id}">查看此能力的全部知识 →</button></article>`).join('')}</div><p class="fine-print">这是依据公开教学标准编制的教学能力图谱，不是实时招聘分析或已训练人岗匹配模型的输出。每个维度仅有1道诊断题，结果只作学习提示。</p>`;}
export function diagnosisResults(state){const d=diagnose(state.answers);if(!state.assessed)return `<div class="empty-state"><span class="empty-number">06</span><h2>为这次学习，找一个起点。</h2><p>完成6道题后，查看答题依据与需要优先复习的知识。</p></div>`;
 return `<div class="diagnosis-score"><span>本次诊断正确率</span><strong>${d.score??0}<small>%</small></strong><p>${d.correct} / ${d.completed} 题答对</p></div><div class="dimension-list">${d.dimensions.map(s=>`<div><span>${s.name}</span><strong class="${s.score===100?'positive':'negative'}">${s.score===null?'未作答':s.score===100?'答对':'待复习'}</strong></div>`).join('')}</div><h3>建议学习顺序</h3>${d.recommendations.length?d.recommendations.map((s,i)=>`<div class="recommendation"><b>${i+1}</b><div><strong>${s.name}</strong><p>先阅读知识，再回到实训验证。</p><button class="text-button" data-knowledge="${s.resources[0]}">学习 ${esc(knowledge.find(k=>k.id===s.resources[0])?.title)} ↗</button></div></div>`).join(''):'<div class="result-note"><strong>当前6道题均已答对。</strong><p>试试进阶实训：改变弹性和库存，检查你的定价建议是否仍然成立。</p></div>'}<p class="fine-print">这是一次小样本知识检查，不能等同于完整岗位胜任力认证。记录保存在本机。</p>`;
}
export function diagnosisView(state){return heading('个性化自适应学习','先定位问题，再安排下一步。','用6道情境题检查关键知识；按答题结果推荐复习路径。')+`<div class="diagnosis-layout"><form id="diagnosis-form"><div class="questions">${questions.map((q,i)=>`<fieldset class="panel question"><legend><span>${String(i+1).padStart(2,'0')} / ${skills.find(s=>s.id===q.skill).name}</span><strong>${q.text}</strong></legend>${q.options.map((o,j)=>`<label class="answer-option"><input type="radio" name="${q.id}" value="${j}" ${state.answers[q.id]===j?'checked':''} required><span><b>${'ABC'[j]}</b>${o}</span></label>`).join('')}${state.assessed?`<div class="answer-explanation"><strong>${state.answers[q.id]===q.answer?'回答正确':'建议复习'} · 正确选项 ${'ABC'[q.answer]}</strong><p>${q.explanation}</p><button class="text-button" type="button" data-knowledge="${q.knowledgeId}">查看知识依据 ↗</button></div>`:''}</fieldset>`).join('')}</div><button type="submit" class="button primary">生成学习建议 <span>→</span></button>${state.assessed?'<button class="button secondary" type="button" data-action="retry-quiz">重新测评</button>':''}</form><aside class="panel diagnosis-summary" id="diagnosis-result">${diagnosisResults(state)}</aside></div>`;}
export function knowledgeCards(query='',skill='all'){const found=searchKnowledge(query,skill);return `<div class="search-count">找到 ${found.length} 条知识 <span>共 ${knowledge.length} 条 · 中文教学改写与原创案例</span></div><div class="knowledge-grid">${found.length?found.map(k=>`<article class="panel knowledge-card"><div class="knowledge-meta"><span>${k.id}</span><span>${skills.find(s=>s.id===k.skill).name}</span></div><h2>${k.title}</h2><p>${k.text}</p><div class="knowledge-card-bottom"><span>${sources[k.sourceId].title.startsWith('Open')?'OpenStax §'+sources[k.sourceId].section.split(' ')[0]:k.sourceId==='nash'?'MIT OCW §6.1':'教育部 2025 教学标准'}</span><button aria-label="查看${k.title}" data-knowledge="${k.id}">↗</button></div></article>`).join(''):'<div class="empty-state"><h2>没有找到相关知识</h2><p>换一个词试试，例如“弹性”“成本”或“信息不对称”。</p></div>'}</div>`;}
export function knowledgeView(state){return heading('专业知识 · 可追溯来源','每一个判断，都能找到依据。',`${knowledge.length}条经济学与岗位知识，连接教材章节、课堂案例和真实工作中的问题。`)+`<div class="knowledge-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input id="knowledge-search" type="search" placeholder="搜索概念、问题或岗位关键词" value="${esc(state.query)}" aria-label="搜索知识库"></label><label class="sr-only" for="knowledge-filter">筛选能力</label><select id="knowledge-filter"><option value="all">全部能力</option>${skills.map(s=>`<option value="${s.id}" ${s.id===state.filter?'selected':''}>${s.name}</option>`).join('')}</select></div><div id="knowledge-results">${knowledgeCards(state.query,state.filter)}</div><p class="fine-print">教材：OpenStax《Principles of Economics 3e》，作者 Greenlaw、Shapiro、MacDonald；中文内容为改写，来源按章节定位。商业平台 MyLab Economics 仅作外部参考，未导入其受限题库。</p>`;}
export function gameResults(state){const {belief,kappa}=state.game,p={belief,kappa,T:5,R:3,P:1,S:0},a=evaluateGame({...p,kappa:0}),b=evaluateGame(p);return `<div class="game-comparison"><article><span class="section-kicker">经济人 · κ = 0</span><h3>选择${a.action==='C'?'合作':'背叛'}</h3><div class="utility"><span>合作效用</span><strong>${number(a.cooperate,2)}</strong></div><div class="utility"><span>背叛效用</span><strong>${number(a.defect,2)}</strong></div><p>只考虑给定信念下自己的预期收益。</p></article><article class="moral-card"><span class="section-kicker">偏好对齐 · κ = ${kappa}</span><h3>${b.action==='tie'?'两种策略效用相同':'选择'+(b.action==='C'?'合作':'背叛')}</h3><div class="utility"><span>合作效用</span><strong>${number(b.cooperate,2)}</strong></div><div class="utility"><span>背叛效用</span><strong>${number(b.defect,2)}</strong></div><p>同时权衡“如果双方都像我这样行动”的结果。</p></article></div><div class="result-note"><strong>行动改变来自目标函数的变化。</strong><p>相同收益矩阵和合作信念下，κ改变了策略评价。κ=0.5不保证所有博弈中都合作，也不表示人格或道德水平。</p></div>`;}
export function gameView(state){return heading('论文机制 · 教学实验','同一个博弈，不同的行动准则。','调整对手合作信念与普遍化权重，比较“经济人”和偏好对齐策略。')+`<div class="game-layout"><section class="panel"><div class="panel-heading"><h2>单轮囚徒困境</h2><span class="tag neutral">合成收益 · 非真人数据</span></div><p>数字依次表示“自己、对手”的收益。双方同时行动，无历史、无沟通。这里演示抽象激励，不用于指导商家串通定价。</p><div class="payoff-wrap"><table class="payoff-table"><caption>课堂设定：T=5，R=3，P=1，S=0</caption><thead><tr><th>自己 ↓ / 对手 →</th><th>合作 C</th><th>背叛 D</th></tr></thead><tbody><tr><th>合作 C</th><td><strong>3 , 3</strong><small>双方合作</small></td><td><strong>0 , 5</strong><small>自己被背叛</small></td></tr><tr><th>背叛 D</th><td><strong>5 , 0</strong><small>对手被背叛</small></td><td><strong>1 , 1</strong><small>双方背叛</small></td></tr></tbody></table></div><div class="game-sliders"><label class="slider-field" for="belief"><span>相信对手合作的概率 q<output id="belief-value">${state.game.belief}</output></span><input type="range" id="belief" min="0" max="1" step="0.05" value="${state.game.belief}" data-game="belief"></label><label class="slider-field" for="kappa"><span>普遍化权重 κ<output id="kappa-value">${state.game.kappa}</output></span><input type="range" id="kappa" min="0" max="1" step="0.05" value="${state.game.kappa}" data-game="kappa"></label></div><div id="game-result">${gameResults(state)}</div></section><aside class="panel theory-panel"><span class="section-kicker">从公式理解机制</span><h2>如果每个人<br>都这样做呢？</h2><div class="formula">U(C) = (1−κ) × qR + κR<br>U(D) = (1−κ) × [qT+(1−q)P] + κP</div><p>由于本例S=0，合作的普通预期收益为qR。κ部分分别使用双方合作的R和双方背叛的P。</p><p>依据用户提供的《大型语言模型智能体与理性及道德偏好的对齐：一种监督微调方法》（yile wang，2026-08-08）第3.3节公式(1)，设不平等厌恶参数α=β=0，作单阶段教学简化。</p><div class="result-note"><strong>本页实际做了什么</strong><p>在浏览器直接求解两个行动的效用；没有训练或调用论文中的微调模型，也不复现其统计结论。</p></div><h3>继续理解博弈</h3>${sourceLinks(['game'])}<button class="text-button" data-knowledge="K054">查看纳什均衡 →</button></aside></div>`;}
export function guideView(){return heading('体验说明','一条链接，完成一次实训。','可直接使用，无需账号、API密钥或本地安装。')+`<div class="guide-grid"><section class="panel guide-primary"><h2>建议按这个顺序体验</h2><ol class="guide-steps"><li><strong>调整价格，先观察结果</strong><p>进入实训工作台，将售价100元调为80元，比较销量、收入和利润，再把库存调为1100件。</p></li><li><strong>向导师连续追问</strong><p>输入“需求价格弹性”，接着问“举个例子”“依据是什么”。输入“这个怎么弄”可体验澄清引导。</p></li><li><strong>完成测评并查看学习路径</strong><p>学习诊断包含6道题。系统根据实际作答标出需复习维度，并链接知识条目。</p></li><li><strong>写出判断，导出实训报告</strong><p>回到工作台，写下建议和假设。导出报告包含参数、结果、任务进度、测评和来源。</p></li></ol><button class="button primary" data-action="start-workspace">开始体验 <span>→</span></button></section><section class="panel"><h2>专业与场景</h2><dl class="definition-list"><dt>专业群</dt><dd>财经商贸专业群，电子商务专业（530701）</dd><dt>典型岗位</dt><dd>电子商务运营专员</dd><dt>教学痛点</dt><dd>促销分析中容易把收入增加等同于利润提高，忽略单位贡献、库存和模型假设。</dd><dt>覆盖方向</dt><dd>岗位能力图谱、工作任务转学习任务、个性化自适应学习。</dd><dt>场景依据</dt><dd>公开专业教学标准与经济学教材；当前案例为教学设计，尚未获得一线访谈证据。</dd></dl>${sourceLinks(['standard'])}</section><section class="panel"><h2>实现与数据边界</h2><p>页面、知识检索、对话上下文、任务规则、数值实验和测评均在浏览器运行。当前未连接MetaGPT服务、外部大模型或训练后的人岗匹配模型。</p><p>所有经营数字均为教学模拟。学习记录存于浏览器本地；试用反馈由你主动导出文件，不会自动发给团队。清除浏览器数据会删除记录。</p><p>AI生成内容标识：本版本输出由内置知识与规则生成；请结合来源核对，不能作为实际经营决策的唯一依据。</p><button class="button secondary" data-action="clear-data">清除本机学习记录</button></section><section class="panel"><h2>比赛材料的实际状态</h2><p>本网页是可体验的MVP。网页与程序自测不能代替真实师生试用反馈。</p><ul class="plain-list"><li>需由2—3名目标专业学生或教师真实试用。</li><li>报名表、PPT、签章声明和演示视频需另行核对整理。</li><li>未声明已经报名、完成真实试用或提交比赛。</li></ul><button class="button secondary" data-action="feedback">填写并导出试用反馈 <span>↗</span></button></section><section class="panel resource-panel"><h2>资源与复现</h2><a href="./docs/demo-guide.md" target="_blank">Demo 使用说明 ↗</a><a href="./docs/technical.md" target="_blank">实现说明与复现方法 ↗</a><a href="./docs/sources.md" target="_blank">知识来源与许可说明 ↗</a><a href="https://github.com/lzh-ff/kedaxunfei" target="_blank" rel="noopener noreferrer">项目代码 ↗</a><a href="https://www.pearson.com/en-gb/higher-education/products-services/mylab/mylab-economics.html" target="_blank" rel="noopener noreferrer">Pearson MyLab Economics（外部参考，需授权访问）↗</a></section></div>`;}
